### ISSUE TITLE
I have some few questions on using Bytecarts

### ISSUE THREAD

**Issue by gomsoop** [catageek/ByteCart#35]
After seeing your replies about the right sided reply, I just decided not to use the router and just stick with an one-line system :) So here are my questions.

1. Is it impossible to have more than 15 stations by manually adding signs? I'm planning to not make a circular line.

2. Can I name same station id on both sides of the stations?

3. Is there a sign, which identifies the ticket(book)s' region and ring number, and if it doesn't match, the rail turns to head hack to the station?

So, since I'm not going to use the auto scanning and updating feature, I guess I can use the rings number as lines? The reasons why I want to use this simple as possible and manually is that my server is just for 4-5 players, and we really don't have that much stations planned. I think ByteCart will have powers on many servers that have more players, but for us, we want it simple :)

I just read the whole plugin again this time and found out that this plugin is the exact thing that I dreamed. Thank you for developing it!

**Comment by thiefa** [comment]
hi, 
routers can be pain in the ass, if something somehow goes wrong. however if they work, they're just a god's gift :)
from my point, i totally recommend using routers, as it makes possible to have shortlinks, multilinks and other nice stuff.



but if you really want to go without a router, your fine too.
you then use just one region with one ring. like 1.1.xxx, allowing you to have all stations that are possible in that ring (255). you then only need to run a  "bcupdater local 1". or you hand out the station numbers manually so you don't need any updater at all.


the biggest breakdowns in this scenario are:
- that you still have to build a ring with start and end put together
- users just can drive clockwise. so if you want to go to a station that would be just the next station counter clockwise, you still have to go aaaaalllll arround the ring clockwise to get to the station.



as for how to build it:
http://www.dailymotion.com/video/x10p1b4_bytecart-tutorial-2-a-simple-network_videogames

https://github.com/catageek/ByteCart/wiki/Step-1-:-A-simple-circular-line
instead of just 1.1.1 to 1.1.4 you can use 1.1.1 - 1.1.255, as long as the ring is closed. 




check any number of servers that run bc to check the usefullness of routers ;) esp. if you going to have long distances between stations...


hope i could help you
thief

**Comment by catageek** [comment]
Hi,

Thanks a lot @thiefa you are the king !

@gomsoop Let us know if you are OK with the answer of @thiefa. I have nothing to add except that I hope you will have fun with your rail network.

catageek

**Comment by thiefa** [comment]
hehe, 
just helping to spread the word :d

had my good share of exp with bc, till to my current setup.


if you remember my first exel-sheet i send you with my track-setup back then, with no routers but all mixed regions and rings, routing with BC7037 and BC7137 signs :)
i cant remember how often i redid all signs because i had a hickup in the signs, or not enough numbers for stations left.
