### ISSUE TITLE
Dynmap Signs not showing Stations properly anymore? 

### ISSUE THREAD

**Issue by thiefa** [catageek/ByteCart#36]
hi, 
i just added a new station, and figured out that dynmap dosent show the name anymore, but just the adress. (older stations are shown as usuall (name, followed by adress))
im using dynmap 2.1, with spigot 1.8.3 and bc 2.9.1

cant say for sure if its an actually a bc issue or not, as i havent added stations recently.
will do some tests, but maybe you have an idea just away..

**Comment by catageek** [comment]
Hi thiefa,

The last version changes a lot the way station names are managed in ByteCart. There may be a bug since It a very fresh feature.

When you create a station without specifying a name, the real name of the station is empty and only the IP is showed on dynmap. There are no more default names.

When you specify a name, then the name is displayed on dynmap with the IP between parenthesis.

There are some new commands to list stations with names associated to an IP (bclist and hostname). If your station does not appear there, you must assume that the station is identified by its IP, has no name and only the IP is displayed on dynmap.

If you think there is a bug, please specify what you wrote on the 3rd line of the sign, what appears when you type bclist (or hostname) after creating the sign and what appears on dynmap.

Catageek

**Comment by thiefa** [comment]
hi catageek, 
sorry for the long delay, we had/have some cat troubels with our new furry fellows :(

As for the issue:
i wrote on the sign:
2. Line: [BC9001]
3. Line: Station Name
4. Line: Adress

Now in dynmap i only see the adress, not the as befor "stationname (adress)"
it only applies to new stations, old ones are fine. i guess because theire allready imported to dynmap.
having an adress shown in dynmap is a nice thing, but a station name makes it easier.
