### ISSUE TITLE
Multible backbones

### ISSUE THREAD

**Issue by thiefa** [catageek/ByteCart#42]
Hi Catageek,

can you tell me if its possible to have multible backbones that connect the same regions? 

My setup is that i have made regions of each 10k blocks in diameter, connected with a teleporter enhanced backbonerail in the middle of each region. 
so far that works  like "i never ever will miss that railway anymore" but now that the habitable spaces closes to the boarder of some regions, i wonder if its possible to connect them trough extra backbones, so if i want to travel to my neighbour next house but other region, i dont have to travel basicly 10k+ blocks to get there, what would be 400 blocks straight line...

may i also suggest "posting" your plugin on spigot as there are allot people?

**Comment by catageek** [comment]
Hi Thiefa, and Happy New Year !

You can have as many backbones as you want. To connect a second backbone to a region, link the 8020 router of the backbone to any 8010 router in the region with some rails, place yourself between the 2 routers and launch the bcupdater region from this point toward the region as if it was a new region, i.e either force X.0.0 as address on the 8010 sign or leave it blank and use the --new flag. In fact it is the same procedure used when you initialize the first router of the network.

The bcupdater will add a new route to ring '0' and propagate it in the region. the route selected to go to the backbone will be the one that takes the less time, so routers will choose the nearest 8020 router to send carts to and your region will be split in two halves relative to the backbone used. there is no way to change the behaviour.

If you want to choose yourself the routers that will use the new backbone and not use the pathfinding algorithm, there is a hacking trick. You must manually split the network in 2 parts (or move the books in the chest above the router to another cell in routers you do not want to modify) , configure the part connected to the new backbone as above, and rebuild the rails after. Each run of bcupdater after this will erase the configuration so you must repeat it.

You should also set EmptyCartsDefaultRoute and PlayersNoTicketDefaultRoute to an address if not already done, because '0.0.0' is ambiguous: some carts will go to the first backbone, while others will go to the second, unless it is the desired behaviour...

About posting my plugin on Spigot, it is a good idea. Did you mean posting myself an announce, or did you propose to do it ?

Catageek

**Comment by thiefa** [comment]
ahh..
ok, thanks for the detailed explanation, wasnt to sure about that multible backbone thingy :)
thats just awesome  :)

just 1 little more bugging for now ;) :
if i would make an recycler on any separatet Backbone because i just connect 2 or 3 regions, thus got 1 connection free anyway, then im fine with 0.0.0 as they just would go to the nearest backbone anyway, did i got that right?


as for announcing on spigot:
can do that for you if you wish, but as its your plugin, ill not doing anything without your explicite permit.


PS: got 15 regions meanwhile, including some that are on different spigot servers, connectet to the same railwaysystem as the others over bungee :)
just love how that thing works :)

please never ever stop keep it combatible with mc versions if needed ;)

**Comment by catageek** [comment]
Yes, that's OK to use 0.0.0 if you have a recycler in each backbone.

I will make an announce on Spigot, but I have to fix the damn pictures of the Wiki before. I am still procrastinating it. There is also a Sponge version of the plugin in preparation, but I am waiting the API to be mature before diving into the code.

I will also visit your server someday. Bytecart with bungee portals must be great. you really should make a video.
