### ISSUE TITLE
constantspeed: true

### ISSUE THREAD

**Issue by ardentcrest** [catageek/ByteCart#45]
Hi. Me again

I have constantspeed set to true but the cart I'm in slows down and stops. carts with chests seem to work ok.

**Comment by catageek** [comment]
Hi,

Do you have other plugins installed ? Try to deactivate them and test again. It's curious that only carts with passengers are affected.

**Comment by ardentcrest** [comment]
just found they slow down but dont stop. 
Will check other plugins

**Comment by ardentcrest** [comment]
All plugins deactivated, apart from bytecart still slows down to a crawl. and when I jump out of it it speeds up again.

**Comment by ardentcrest** [comment]
PS just to let you know I did a mego 2.2.5 (the farm) from across the map. climbed aboard a train from Vehicles (No resourcepacks needed!) and arrived at the farm :D

**Comment by catageek** [comment]
I could reproduce the bug, but I have currently no idea of the cause. I need to investigate.

**Comment by ardentcrest** [comment]
As traincart is no more I really want to use your plugin. so until you find a fix it looks as im going to have to use power rails for the time been.

**Comment by ardentcrest** [comment]
Hi. Do you know of any online severs that use your great pluigin.

**Comment by ardentcrest** [comment]
Sorry :). another some more questions.

is there a way to hide the blocks with the redstone at the stations so you just see the tracks.
and

I want to place alot underground. does the chest in the air above the router have to be there or can it be put somewhere else.

**Comment by catageek** [comment]
Hi,
@thiefa has a great server that uses my plugin and is usually happy to help Bytecart users. Unfortunately I lost the address of his server. He is also thief001 on bukkit.org, and probably a user of mcspigot forum. You may contact him there.

To hide the redstone in the stations, you must know that the plugin only activate the lever on the left or on the right of the sign. You can change the lever attachment face and put it on the ground (for example),  then conduct the signal under the T to change the direction of the rail. There must be some redstone engineering to do this.

The chest above the router must be here, but I can define an alternate position under the ground in a next version.

**Comment by catageek** [comment]
Seems that 1.9.4 is not affected, while 1.10.2 is affected. I still don't have any clue.

**Comment by thiefa** [comment]
Hi catageek, 
would be sweet if that chest could go hidden :) :) :)

had some users that where complaining about it, esp. since its a double chest and thus not sitting in the middle of the core. no way to mask her properly in a pillar...

my server runs at pia.hopto.org:25566 ;)
guest accs are enabled, so looking around and having a ride is gogo ;)


always happy to help, hopefully makes catageek keep bytecart alive for a looooong time :)

@ardentcrest as you asked it another issue: yes porting minecarts is totally possible, as catageek stated, ill do it even over bungeecord between different servers. its sweet ;)

if tried a few plugins for that, currently "stuck" on  [Ancient gates reloadet](https://dev.bukkit.org/projects/ancientgates-reloaded)

but there are other plugins aswell that claim to be able to tp carts between servers

**Comment by catageek** [comment]
@thiefa This will be my next commit, and a release soon.

**Comment by catageek** [comment]
@thiefa Double chests are not mandatory and can be replaced by Simple chests.

**Comment by thiefa** [comment]
Double chests are not needed in 3.0.0 anymore, or never where?

just always saw the routers in your tut-world and everywhere with double chest, so i dint even think about trying single chest routers

o my, someone has to go and cut alllooot chests ^^
*grabs wood saw*

**Comment by catageek** [comment]
@thiefa In fact they were never needed since the start, but in ByteCart 1.0 (back in 2013) I used the material in the inventory to code the routes, so I needed some large capacity. I never had the idea to show that a simple chest was enough since 2.0, like I never had the idea to put it below the router.
