### ISSUE TITLE
Pathfinding issue with V3

### ISSUE THREAD

**Issue by thiefa** [catageek/ByteCart#49]
Hi, 
just updated to test your lastest v3 ByteCart-3.1.0-20170415.132119-1.jar, (Spigot 1.11.2) but since i have it on server, the carts stuck everywhere between routers and dont find there ways to the destination anymore.

**Comment by ardentcrest** [comment]
My dont get stuck, they do go to its destination, but does not go in to the station but just keeps going past the turn for it.

**Comment by catageek** [comment]
@thiefa You do not use the last version, the snapshot you use has a bug. Please download the last version from spigotmc repository.

@ardentcrest your issue is not related to this one... The carts don't stop if the lever next to the platform is on. You must swith off the lever after you make leave a cart, or replace the lever by a button.

**Comment by thiefa** [comment]
Hi catageek, 
yep, pathfinding works now :)

however, BC9001 Station signs dont switch to let carts get in to the station, even if the ticket matchs.. i get the message, but nothing happens else.. if i try with a wrong one, i dont get in either. so they are not just switching inverted.
also the BC9037 and BC9137 dont switch the track.
