### ISSUE TITLE
Few problems that i find odd

### ISSUE THREAD

**Issue by MrKiller01** [catageek/ByteCart#51]
Hi, at first, at almost the exact same time as a colleague, dynmap stopped showing updater carts throughout the dynmap world. It shows the players, stations residence areas etc... Not the updater that is active.
2nd is the lack of 'find any updater still active' option. I really miss this the bigger the tracks get, the harder it is to keep track...
3rd why does updater cart keep getting the same route over and over again and not progress on the track. There are a great number of routers waiting for the updater, that never shows up, even if the tracks are visually checked.
4th Is there a programmable option or command that we can give to make a preliminary test to find out if the tracks in question are ok, not broken or missing parts etc... This is also a big help for bigger systems...
5th what is your time for vacation? I guess that you have enough naggers like me at your door, but you started with building this magnificent plugin (-: 

Thanks for a great time by the way...

**Comment by thiefa** [comment]
hi, 
as for your question 1:
its solved on my server with the lastest dynmap-head 
(besides a bug when the updater still updates after some kind of timeout, where the updater icon stays on place on dynmap)


as for q2:
theres a command to remove the property of the updater, so hes just an simple chestcart. 
its still not locatable, but it makes sure you can launch another updater after some time without risk of missconfigured network because of two updaters in the same region.

catageek:
"You can use 'bcupdater remove' to remove the updater property of a cart when it will pass on any BC sign. This does not remove physically the cart, but stops the update immediately."


q3: 
ill join on your server and we will have a look :)


q4:
none (yet?) 
might be hard to do, as chunks are not loaded where tracks are.. might kill many server to keep all chunks with tracks loaded for a check.

q5:
im nagging too :P

**Comment by catageek** [comment]
For q2, I can make a command that will tell the last known position of updaters.

For q4: Bytecart has only a logical view of the network, and activates levers for routing carts. It does not know what a rail is. If rail verification were to be done, it will be a huge work since all the physical network must be modelled. It's also a completely different plugin.

**Comment by thiefa** [comment]
hi catageek, 
a command to get the last know position of updaters would be really awesome :)
